variables:
  REG: 'GitHub Packages'
  REP: '$(Build.Repository.Name)/'
  IMG: 'docker.pkg.github.com/$(Build.Repository.Name)/'
  TAG: 'ltsc2019'

jobs:
  - job: base
    timeoutInMinutes: 30
    pool:
      vmImage: 'windows-2019'
    steps:
    - script: ver
      displayName: print host version
    - task: Docker@2
      displayName: build base
      inputs:
        command: build
        containerRegistry: '$(REG)'
        repository: '$(REP)base'
        tags: '$(TAG)'
        Dockerfile: 'Dockerfile.base'
        arguments: '--build-arg BASE_TAG=$(TAG)'
    - task: Docker@2
      displayName: push base
      inputs:
        command: push
        containerRegistry: '$(REG)'
        repository: '$(REP)base'
        tags: '$(TAG)'

  - job: msys2
    dependsOn: base
    timeoutInMinutes: 60
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: Docker@2
      displayName: build msys2
      inputs:
        command: build
        containerRegistry: '$(REG)'
        repository: '$(REP)msys2'
        tags: '$(TAG)'
        Dockerfile: 'Dockerfile.msys2'
        arguments: '--build-arg BASE_IMG=$(IMG)base --build-arg BASE_TAG=$(TAG)'
    - task: Docker@2
      displayName: push msys2
      inputs:
        command: push
        containerRegistry: '$(REG)'
        repository: '$(REP)msys2'
        tags: '$(TAG)'

  - job: msys2_mingw32
    dependsOn: msys2
    timeoutInMinutes: 90
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: Docker@2
      displayName: build msys2-mingw32
      inputs:
        command: build
        containerRegistry: '$(REG)'
        repository: '$(REP)msys2-mingw32'
        tags: '$(TAG)'
        Dockerfile: 'Dockerfile.msys2-mingw32'
        arguments: '--build-arg BASE_IMG=$(IMG)msys2 --build-arg BASE_TAG=$(TAG)'
    - task: Docker@2
      displayName: push msys2-mingw32
      inputs:
        command: push
        containerRegistry: '$(REG)'
        repository: '$(REP)msys2-mingw32'
        tags: '$(TAG)'

  - job: msys2_mingw64
    dependsOn: msys2
    timeoutInMinutes: 90
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: Docker@2
      displayName: build msys2-mingw64
      inputs:
        command: build
        containerRegistry: '$(REG)'
        repository: '$(REP)msys2-mingw64'
        tags: '$(TAG)'
        Dockerfile: 'Dockerfile.msys2-mingw64'
        arguments: '--build-arg BASE_IMG=$(IMG)msys2 --build-arg BASE_TAG=$(TAG)'
    - task: Docker@2
      displayName: push msys2-mingw64
      inputs:
        command: push
        containerRegistry: '$(REG)'
        repository: '$(REP)msys2-mingw64'
        tags: '$(TAG)'

  - job: msys1_mingw
    dependsOn: base
    timeoutInMinutes: 60
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: Docker@2
      displayName: build msys1-mingw
      inputs:
        command: build
        containerRegistry: '$(REG)'
        repository: '$(REP)msys1-mingw'
        tags: '$(TAG)'
        Dockerfile: 'Dockerfile.msys1-mingw'
        arguments: '--build-arg BASE_IMG=$(IMG)base --build-arg BASE_TAG=$(TAG)'
    - task: Docker@2
      displayName: push msys1-mingw
      inputs:
        command: push
        containerRegistry: '$(REG)'
        repository: '$(REP)msys1-mingw'
        tags: '$(TAG)'

  - job: msys1_mingw32
    dependsOn: msys1_mingw
    timeoutInMinutes: 60
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: Docker@2
      displayName: build msys1-mingw32
      inputs:
        command: build
        containerRegistry: '$(REG)'
        repository: '$(REP)msys1-mingw32'
        tags: '$(TAG)'
        Dockerfile: 'Dockerfile.msys1-mingw32'
        arguments: '--build-arg BASE_IMG=$(IMG)msys1-mingw --build-arg BASE_TAG=$(TAG)'
    - task: Docker@2
      displayName: push msys1-mingw32
      inputs:
        command: push
        containerRegistry: '$(REG)'
        repository: '$(REP)msys1-mingw32'
        tags: '$(TAG)'

  - job: msys1_mingw64
    dependsOn: msys1_mingw
    timeoutInMinutes: 60
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: Docker@2
      displayName: build msys1-mingw64
      inputs:
        command: build
        containerRegistry: '$(REG)'
        repository: '$(REP)msys1-mingw64'
        tags: '$(TAG)'
        Dockerfile: 'Dockerfile.msys1-mingw64'
        arguments: '--build-arg BASE_IMG=$(IMG)msys1-mingw --build-arg BASE_TAG=$(TAG)'
    - task: Docker@2
      displayName: push msys1-mingw64
      inputs:
        command: push
        containerRegistry: '$(REG)'
        repository: '$(REP)msys1-mingw64'
        tags: '$(TAG)'
